#!/usr/bin/env python3
"""A tiny directory-driven static site generator backed by Typst HTML."""

from __future__ import annotations

import argparse
import json
import os
import posixpath
import shutil
import subprocess
import sys
import tempfile
from dataclasses import dataclass, field
from datetime import datetime
from pathlib import Path, PurePosixPath


@dataclass
class Node:
    parts: tuple[str, ...]
    source: Path
    alias: str = ""
    children: list["Node"] = field(default_factory=list)

    @property
    def updated(self) -> datetime:
        return datetime.fromtimestamp(self.source.stat().st_mtime).astimezone()

    @property
    def route(self) -> str:
        return "/" if not self.parts else "/" + "/".join(self.parts) + "/"

    @property
    def output(self) -> str:
        return "index.html" if not self.parts else "/".join((*self.parts, "index.html"))


class SiteError(Exception):
    pass


def typst_string(value: str) -> str:
    """JSON strings and Typst strings share the escaping needed here."""
    return json.dumps(value, ensure_ascii=False)


def is_private(parts: tuple[str, ...]) -> bool:
    return any(part.startswith("_") or part.startswith(".") for part in parts)


def discover(content_dir: Path) -> tuple[Node, list[Node]]:
    root_index = content_dir / "index.typ"
    if not root_index.is_file():
        raise SiteError(f"missing root content file: {root_index}")

    by_parts: dict[tuple[str, ...], Node] = {}
    for source in sorted(content_dir.rglob("index.typ")):
        parts = tuple(source.parent.relative_to(content_dir).parts)
        if is_private(parts):
            continue
        by_parts[parts] = Node(parts=parts, source=source)

    for parts in sorted(by_parts, key=lambda item: (len(item), item)):
        if not parts:
            continue
        parent_parts = parts[:-1]
        if parent_parts not in by_parts:
            route = "/" + "/".join(parts) + "/"
            parent_route = "/" if not parent_parts else "/" + "/".join(parent_parts) + "/"
            raise SiteError(
                f"content node {route} has no parent node {parent_route}; "
                f"add {content_dir.joinpath(*parent_parts, 'index.typ')}"
            )
        by_parts[parent_parts].children.append(by_parts[parts])

    nodes = sorted(by_parts.values(), key=lambda node: node.parts)
    for index, node in enumerate(nodes):
        node.alias = f"page_{index}"
    return by_parts[()], nodes


def relative_href(current: Node, target: Node) -> str:
    current_dir = "/".join(current.parts) or "."
    target_dir = "/".join(target.parts) or "."
    relative = posixpath.relpath(target_dir, current_dir)
    return "./" if relative == "." else relative.rstrip("/") + "/"


def project_path(path: Path, project_root: Path) -> str:
    relative = path.resolve().relative_to(project_root.resolve())
    return "/" + PurePosixPath(relative).as_posix()


def render_tuple(items: list[str], indent: int = 0) -> str:
    if not items:
        return "()"
    padding = " " * indent
    inner = "\n".join(f"{padding}  {item}," for item in items)
    return f"(\n{inner}\n{padding})"


def generate_entry(project_root: Path, theme_file: Path, root: Node, nodes: list[Node]) -> str:
    style_file = theme_file.with_name("style.typ")
    lines = [
        "// Generated by ssg.py. Do not edit.",
        f'#import {typst_string(project_path(theme_file, project_root))}: render',
        f'#import {typst_string(project_path(style_file, project_root))}: emit-theme-assets',
    ]

    for node in nodes:
        source = project_path(node.source, project_root)
        lines.append(f'#import {typst_string(source)} as {node.alias}')

    lines.append("")

    # Children point to node variables, so emit leaves before their parents.
    for node in sorted(nodes, key=lambda item: len(item.parts), reverse=True):
        child_values = [f"node_{child.alias}" for child in node.children]
        links = [
            f'{target.alias}: {typst_string(relative_href(node, target))}'
            for target in nodes
        ]
        root_prefix = "../" * len(node.parts)
        updated = node.updated
        updated_date = updated.date().isoformat()
        lines.extend(
            [
                f"#let node_{node.alias} = (",
                f'  id: {typst_string(node.alias)},',
                f'  route: {typst_string(node.route)},',
                f'  root-prefix: {typst_string(root_prefix)},',
                f'  updated: {typst_string(updated_date)},',
                f"  page: {node.alias}.page,",
                f"  links: {render_tuple(links, 2)},",
                f"  children: {render_tuple(child_values, 2)},",
                ")",
                "",
            ]
        )

    lines.append(f"#let site = node_{root.alias}")
    lines.append("")
    lines.append("#emit-theme-assets()")
    lines.append("")

    for node in nodes:
        lines.extend(
            [
                f"#document({typst_string(node.output)}, title: {node.alias}.page.title)[",
                f"  #render({node.alias}.page, node_{node.alias}, site)",
                "]",
                "",
            ]
        )

    return "\n".join(lines)


def copy_assets(source_root: Path, destination_root: Path) -> None:
    if not source_root.exists():
        return
    for source in source_root.rglob("*"):
        if not source.is_file():
            continue
        relative = source.relative_to(source_root)
        if is_private(tuple(relative.parts)) or source.suffix == ".typ":
            continue
        destination = destination_root / relative
        if destination.exists():
            raise SiteError(f"asset would overwrite generated output: {relative}")
        destination.parent.mkdir(parents=True, exist_ok=True)
        shutil.copy2(source, destination)


def validate_output(project_root: Path, output: Path) -> Path:
    resolved_root = project_root.resolve()
    resolved_output = output.resolve()
    if resolved_output == resolved_root or resolved_root not in resolved_output.parents:
        raise SiteError("output directory must be inside the project and cannot be the project root")
    return resolved_output


def build(project_root: Path, output: Path, keep_entry: bool = False) -> None:
    content_dir = project_root / "content"
    theme_file = project_root / "theme" / "render.typ"
    style_file = project_root / "theme" / "style.typ"
    cache_dir = project_root / ".ssg"

    if not theme_file.is_file():
        raise SiteError(f"missing theme renderer: {theme_file}")
    if not style_file.is_file():
        raise SiteError(f"missing theme style module: {style_file}")

    root, nodes = discover(content_dir)
    cache_dir.mkdir(exist_ok=True)
    entry_file = cache_dir / "site.typ"
    entry_file.write_text(
        generate_entry(project_root, theme_file, root, nodes),
        encoding="utf-8",
    )

    output = validate_output(project_root, output)
    temporary = Path(tempfile.mkdtemp(prefix=".ssg-build-", dir=project_root))
    try:
        command = [
            "typst",
            "compile",
            "--root",
            str(project_root),
            "--features",
            "html,bundle",
            "--format",
            "bundle",
            "--pretty",
            str(entry_file),
            str(temporary),
        ]
        subprocess.run(command, check=True)
        copy_assets(content_dir, temporary)

        if output.exists():
            shutil.rmtree(output)
        os.replace(temporary, output)
    except SiteError:
        shutil.rmtree(temporary, ignore_errors=True)
        raise
    except (OSError, subprocess.CalledProcessError) as error:
        shutil.rmtree(temporary, ignore_errors=True)
        raise SiteError(f"build failed: {error}") from error
    finally:
        if not keep_entry:
            entry_file.unlink(missing_ok=True)
            try:
                cache_dir.rmdir()
            except OSError:
                pass

    print(f"built {len(nodes)} pages into {output}")


def make_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("command", choices=("build", "inspect"), nargs="?", default="build")
    parser.add_argument("--project", type=Path, default=Path.cwd())
    parser.add_argument("--output", type=Path, default=Path("docs"))
    parser.add_argument("--keep-entry", action="store_true", help="keep .ssg/site.typ after building")
    return parser


def main() -> int:
    args = make_parser().parse_args()
    project_root = args.project.resolve()
    output = args.output if args.output.is_absolute() else project_root / args.output
    try:
        root, nodes = discover(project_root / "content")
        if args.command == "inspect":
            for node in nodes:
                print(f"{node.route:<32} {node.output}")
            return 0
        build(project_root, output, keep_entry=args.keep_entry)
        return 0
    except SiteError as error:
        print(f"error: {error}", file=sys.stderr)
        return 1


if __name__ == "__main__":
    raise SystemExit(main())
